### PR TITLE
Set status to Blocked when secret-key is shorter than 8 characters long

### PR DESCRIPTION
**Pull request by lucabello**
Closes https://github.com/canonical/minio-operator/issues/137.

This PR adds an additional check in the charm.py file to ensure that the `secret-key` is at least 8 characters long. If it isn't, the charm's status changes to blocked with an appropriate message.

The minimum size of 8 characters seems to be hard-coded in [this line](https://github.com/minio/minio/blob/4e67a4027e3c9ba7f294bd71a9000b03c5efad7e/internal/auth/credentials.go#L45).

### CODE REVIEW

**Comment by mvlassis** [comment]
@lucabello I created a PR that introduces the changes you made (to trigger the CI because it only triggers for team members of the repo).

Great work!

**Comment by mvlassis** [comment]
@lucabello Since all the CI passes, it's ready to go! Some small suggestions before we merge:
- Update the PR title and description to be slightly more descriptive (#183 has some information)
- Merge the latest changes from `main` into the branch

Thanks again!

**Comment by lucabello** [comment]
Seems like you have your other PR up so not sure if you still need this one, but updating the things you asked nonetheless :)

**Review by mvlassis — APPROVED** [review]

**Comment by mvlassis** [comment]
@lucabello I created the PR just to trigger the CI, so I just merged yours and closed #183 as a duplicate.

Thanks for contributing :)

**Pull request merged**
